#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <omp.h>

void parallel_bar_chart(int* data, int size, int num_threads) {
    int max_value = 0;
    #pragma omp parallel for reduction(max:max_value) num_threads(num_threads)
    for (int i = 0; i < size; i++) {
        if (data[i] > max_value) {
            max_value = data[i];
        }
    }

    #pragma omp parallel for num_threads(num_threads)
    for (int value = 1; value <= max_value; value++) {
        int count = 0;
        for (int i = 0; i < size; i++) {
            if (data[i] == value) {
                count++;
            }
        }
        if (count > 0) {
            printf("Data Point %d: ", value);
            for (int j = 0; j < count; j++) {
                printf("*");
            }
            printf("\n");
        }
    }
}

// Measure Parallel Execution Time (large dataset)
void measure_parallel_performance(int size, int num_threads) {
    int* data = (int*)malloc(size * sizeof(int));
    if (!data) {
        printf("Memory allocation failed.\n");
        return;
    }

    srand(time(NULL));
    for (int i = 0; i < size; i++) {
        data[i] = rand() % 100 + 1;
    }

    double total_time = 0.0;

    for (int run = 1; run <= 10; run++) {
        double start = omp_get_wtime();

        int max_value = 0;
        #pragma omp parallel for reduction(max:max_value) num_threads(num_threads)
        for (int i = 0; i < size; i++) {
            if (data[i] > max_value) {
                max_value = data[i];
            }
        }

        #pragma omp parallel for num_threads(num_threads)
        for (int value = 1; value <= max_value; value++) {
            int count = 0;
            for (int i = 0; i < size; i++) {
                if (data[i] == value) {
                    count++;
                }
            }
        }

        double end = omp_get_wtime();
        double run_time = end - start;
        total_time += run_time;
        printf("Run %d time: %f seconds\n", run, run_time);
    }

    printf("\nAverage Time over 10 runs: %f seconds\n", total_time / 10.0);

    free(data);
}

int main() {
    int mode;
    printf("Select mode:\n");
    printf("1. Parallel bar chart (User data)\n");
    printf("2. Parallel performance test (Autogenerated 1M dataset)\n");
    scanf("%d", &mode);

    if (mode == 1) {
        int size, num_threads;
        printf("Enter dataset size: ");
        scanf("%d", &size);

        int* data = (int*)malloc(size * sizeof(int));
        if (!data) {
            printf("Memory allocation failed.\n");
            return 1;
        }

        printf("Enter dataset values separated by spaces:\n");
        for (int i = 0; i < size; i++) {
            scanf("%d", &data[i]);
        }

        printf("Enter number of threads: ");
        scanf("%d", &num_threads);

        double start = omp_get_wtime();
        parallel_bar_chart(data, size, num_threads);
        double end = omp_get_wtime();

        printf("\nTime taken (Parallel): %f seconds\n", end - start);

        free(data);

    } else if (mode == 2) {
        int num_threads;
        printf("Enter number of threads: ");
        scanf("%d", &num_threads);

        measure_parallel_performance(1000000, num_threads);
    } else {
        printf("Invalid choice.\n");
    }

    return 0;
}
