
// to compile and run this code 👇🏻
// gcc -o SequentialBarChart SequentialBarChart.c        (Compile)
// SequentialBarChart.exe (for windows)                  (Run)
// ./SequentialBarChart   (for mac)                      (Run)
/*
gcc -o SequentialBarChart SequentialBarChart.c 
./SequentialBarChart
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>  // included to measure time using clock() function

// Sequential Function
void generate_bar_chart(int* data, int size) {
    printf("\n--- Bar chart ---\n");
    for (int i = 0; i < size; i++) {
        printf("Data Point %d: ", i + 1);
        for (int j = 0; j < data[i]; j++) {
            printf("*");
        }
        printf("\n");
    }
}

int main() {

    //------------------------------------------------------
    //             users generated dataset
    //------------------------------------------------------

    int size;
    printf("Enter the dataset size: ");
    scanf("%d", &size);

    int* data = (int*)malloc(size * sizeof(int));
    if (!data) {
        printf("Memory allocation failed.\n");
        return 1;
    }

    printf("Enter the dataset values (separated by spaces): ");
    for (int i = 0; i < size; i++) {
        scanf("%d", &data[i]);
    }

    clock_t start = clock();        // start measuring function time
    generate_bar_chart(data, size);
    clock_t end = clock();          // end measuring function time

    double time_taken = ((double)(end - start)) / CLOCKS_PER_SEC;
    printf("\nTime taken to generate bar chart in Sequential: %.6f seconds\n", time_taken);

    free(data);

    char yn ;
    printf("would you like to see the Autogenerated array ? (y/n)");
    scanf(" %c", &yn); 
    if(yn == 'y' || yn == 'Y'){
        goto Autogenerated;
    }
    goto pass;

    //------------------------------------------------------
    //              Autogenerated dataset
    //------------------------------------------------------
    
    Autogenerated:
    size = 1000000 ;
    int* data2 = (int*)malloc(size * sizeof(int));
    if (!data2) {
        printf("Memory allocation failed.\n");
        return 1;
    }
    srand(time(NULL));
    // Autogenerate dataset values between 1 and 100
    printf("Autogenerated dataset values:\n");
    for (int i = 0; i < size; i++) {
        data2[i] = rand() % 100 + 1;  // generates numbers between 1 and 100
    }
    printf("\n");

    start = clock(); 
    generate_bar_chart(data2, size);
    end = clock(); 

    time_taken = ((double)(end - start)) / CLOCKS_PER_SEC;
    printf("\nAutogenerated dataset in Sequential for %d: %.6f seconds\n",size,time_taken);

    free(data2);

    pass:

    return 0;
}
